name: offchain-modules-ci

on:
  push:
    paths:
      - .github/workflows/offchain-modules.yml
      - 'offchain-modules/**.rs'
      - 'offchain-modules/**/Cargo.toml'
      - 'offchain-modules/**/Cargo.lock'
  pull_request:
    paths:
      - .github/workflows/offchain-modules.yml
      - 'offchain-modules/**.rs'
      - 'offchain-modules/**/Cargo.toml'
      - 'offchain-modules/**/Cargo.lock'

jobs:
  contract-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2020-10-22
          override: true
          components: rustfmt, clippy
      - name: format-contracts
        run: |
          cd offchain-modules
          cargo fmt -- --check
          cargo test -- --nocapture
          cargo clippy -- -D warnings
